name: Validate Salesforce Data CLoud and CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


           
  
  validate:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 'Checkout source code'
      uses: actions/checkout@v2

    # Install SFDX CLI
    - name: Install SFDX CLI
      run: npm install sfdx-cli -g



    #Authorize MyDataCloud org
    - name: Authorize MyDataCloud Org 
      run: sfdx force:auth:jwt:grant --client-id 3MVG9Rr0EZ2YOVMZS97WX10cck5iaCD_PSGwuIbmwlbGesVSMYPbcvE5JWDz02GXlxYAfBsBZz6zvY9RaBdSA --jwt-key-file assets/server.key --username admin@datacloud.workshop11.org --instance-url https://login.salesforce.com
